version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: axioma_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: axioma_secret_password_2026
      POSTGRES_DB: axioma_psicologia_db
    ports:
      - "5433:5432" # Mapeado al puerto 5433 para evitar conflicto con PostgreSQL 18 local en 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
